[package]
name = "revsh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.41"
clap = "2.33.3"
tokio = { version = "1.7.0", features = ["full"] }
tokio-native-tls = "0.3.0"
